//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscarMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class especialidades
    {
        public especialidades()
        {
            this.medicos = new HashSet<medicos>();
        }
    
        public int IDEspecialidade { get; set; }

        // [Required(ErrorMessage = "Campo obrigatorio")]
        //[StringLength(50, ErrorMessage = "O Especialidade deve possuir no maximo 50 caracteres")]
        public string Nome { get; set; }
    
        public virtual ICollection<medicos> medicos { get; set; }
    }
}
