//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscarMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class medicos
    {
        public long IDMedico { get; set; }

        //[Required(ErrorMessage="Campo obrigatorio")]                              NÃO FUNCIONOU, GERANDO UMA EXCEPTION PARA O IDEspecialidade...
        // [StringLength(50, ErrorMessage="O CRM deve possuir no maximo 50 caracteres")]
        public string CRM { get; set; }

        //[Required(ErrorMessage = "Campo obrigatorio")]
        //[StringLength(50, ErrorMessage = "O Nome deve possuir no maximo 50 caracteres")]
        public string Nome { get; set; }

        //[Required(ErrorMessage = "Campo obrigatorio")]
        //[StringLength(80, ErrorMessage = "O Endereco deve possuir no maximo 80 caracteres")]
        public string Endereco { get; set; }

        //[Required(ErrorMessage = "Campo obrigatorio")]
        //[StringLength(50, ErrorMessage = "O Bairro deve possuir no maximo 50 caracteres")]
        public string Bairro { get; set; }

        //[Required(ErrorMessage = "Campo obrigatorio")]
        //[StringLength(80, ErrorMessage = "O Email deve possuir no maximo 80 caracteres")]
        public string Email { get; set; }

        //[Required(ErrorMessage = "Campo obrigatorio")]
        public bool AtendePorConvenio { get; set; }

        // [Required(ErrorMessage = "Campo obrigatorio")]
        public bool TemClinica { get; set; }


        //[StringLength(5, ErrorMessage="O webSite deve possuir no minimo 5 caracteres")]
        public string WebsiteBlog { get; set; }

        // [Required(ErrorMessage = "Campo obrigatorio")]
        public int IDCidade { get; set; }


        public int IDEspecialidade { get; set; }

        public virtual cidades cidades { get; set; }
        public virtual especialidades especialidades { get; set; }
    }
}
