//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscarMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuarios
    {
        public long IDUsuario { get; set; }

        [Required(ErrorMessage = "Campo obrigatorio")]
        [StringLength(50, ErrorMessage = "O Nome deve possuir no maximo 50 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo obrigatorio")]
        [StringLength(50, ErrorMessage = "O Login deve possuir no maximo 50 caracteres")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Campo obrigatorio")]
        [StringLength(100, ErrorMessage = "O  Senha deve possuir no maximo 100 caracteres")]
        public string Senha { get; set; }

        [Required(ErrorMessage = "Campo obrigatorio")]
        [StringLength(50, ErrorMessage = "O Email deve possuir no maximo 50 caracteres")]
        public string Email { get; set; }
    }
}
